site_name: digitalearth
site_description: The documentation of digitalearth python package
site_author: Mostafa Farrag

repo_url: https://github.com/MAfarrag/digitalearth
edit_url: ""

theme:
    name: readthedocs

nav:
    - Home: index.md
    - License: license.md
