{% set version = "0.1.0" %}

package:
  name: digitalearth
  version: {{ version }}

source:
  path: C:\MyComputer\01Algorithms\Visualization\digitalearth

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

channels:
  - conda-forge

requirements:
  host:
  - python>=3.9.0,<3.10
  - pip>=21.3.1
  run:
    - numpy >=1.21.2,<1.22.4
    - gdal >=3.3.3,<3.5.1
    - netCDF4 >=1.5.5,<1.5.9
    - pandas >=1.3.2,<1.4.3
    - ecmwf-api-client >=1.6.1
    - pytest >=6.2.5
    - pytest-cov >=2.12.1
    - pyramids >=0.1.0


test:
  imports:
    - digitalearth

about:
  home: https://github.com/MAfarrag/digitalearth
  license: MIT
  summary: 'GIS utility package'
  description: |
    GIS utility package.
  dev_url: https://github.com/MAfarrag/digitalearth
  doc_url: https://digitalearth.readthedocs.io/en/latest/
  doc_source_url: https://github.com/MAfarrag/digitalearth/main/README.md
